### ISSUE TITLE
NullReference exception thrown when uploading Spreadsheet with colour filled cells.

### ISSUE THREAD

**Issue by j-r-morton** [audaciaconsulting/Audacia.Spreadsheets#8]
Package version: 1.2.1

## Repro steps:
1. Create a spreadsheet and colour some of the cells, ie:
![image](https://github.com/user-attachments/assets/1d6fc420-cef6-410e-b5d0-f5db61526320)
1. Try to import the file using `Spreadsheet.FromStream` (seems like all the methods use this internally anyway, so maybe would work with any method)
1. Expected:
    1. File is read into a `Spreadsheet` object.
1. Actual:
    1. NullReference exception is thrown while reading the file:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Audacia.Spreadsheets.TableRow.GetColor(SpreadsheetDocument sd, PatternFill fill)
   at Audacia.Spreadsheets.TableRow.CreateCellAsSharedString(SpreadsheetDocument spreadSheet, Cell matchedCell, SharedStringTablePart stringTable, CellFormats cellFormats, Stylesheet stylesheet)
   at Audacia.Spreadsheets.TableRow.FromOpenXml(WorksheetPart worksheetPart, SpreadsheetDocument spreadSheet, Int32 columnsCount, Int32 startingRowIndex)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Audacia.Spreadsheets.Worksheet.FromOpenXml(Sheet worksheet, SpreadsheetDocument spreadSheet, Boolean includeHeaders, Boolean hasSubtotals)
   at Audacia.Spreadsheets.Spreadsheet.<>c__DisplayClass14_1.<FromStream>b__1(Sheet sheet)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Audacia.Spreadsheets.Spreadsheet.FromStream(Stream stream, Boolean includeHeaders, Boolean hasSubtotals, IEnumerable`1 ignoreSheets)
```

### Notes:

Spreadsheet was created using Audacia Worksheet Export functionality.
If fill is removed from cells, import works as expected.
Exception does NOT get thrown in our previously installed version 1.1.22077

**Comment by Rachel-Flynn** [comment]
This has been solved in [PR#9](https://github.com/audaciaconsulting/Audacia.Spreadsheets/pull/9)
